### ISSUE TITLE
script hang on this error

### ISSUE THREAD

**Issue by cj4c0b1** [bogdanteodoru/py3cw#7]
HI there
I'm having this hang problem almost every day after some time running fine.
Seems to be a connection related with 3commas but I didn't figure out to solve yet.
It happens on Python 3.6.8 and Python 3.8.3 as far as I tested only on these 2 versions.
this is the error stack after pressing Ctrl-c

`2020-11-11 01:25:10,139-INFO: checking deals on account j4c0b1_3cexchange
^CTraceback (most recent call last):
  File "3ca-audit_deals.py", line 140, in <module>
    error,accounts = p3c.request(entity='accounts',action='')
  File "/home/opc/3ca/py3cw/py3cw/utils.py", line 26, in wrapper
    return func(*args, **kw)
  File "/home/opc/3ca/py3cw/py3cw/request.py", line 119, in request
    api_url_version=api_url_version
  File "/home/opc/3ca/py3cw/py3cw/request.py", line 82, in __make_request
    json=payload
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/urllib3/connection.py", line 371, in connect
    ssl_context=context,
  File "/home/opc/venv/3ca/lib64/python3.6/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
Wed Nov 11 07:54:04 GMT 2020
`

**Comment by bogdanteodoru** [comment]
Hi @cj4c0b1. From what I see seems to be a timeout error. I'm using it too and didn't have that error but recently there were some downtimes with AWS and some connectivity issues in Europe. Maybe that's the case? 

Does the script just hang? or does it throw any errors before you CTRL+C

**Comment by cj4c0b1** [comment]
Just hang.
The errors you see was after Ctrl+C

**Comment by cj4c0b1** [comment]
Hej guys, seems to be a ssl handshake problem that can be solved with a certifi update

`pip install --upgrade certifi`

I'm testing right now, lets see if it works OK until tomorrow!

**Comment by cj4c0b1** [comment]
Hej guys, same error today in the morning...
back to research...

**Comment by cj4c0b1** [comment]
After updating ssl certifi I'm testing another approach, lets see until tomorrow.
If it works i will make a pull request.
Code on branch develop of my fork [https://github.com/bogdanteodoru/py3cw/commit/336691d25f16266e456bc98948ba0c004da3a388](url)

**Comment by cj4c0b1** [comment]
Done @bogdanteodoru #8 
Please merge and be happy!
so, to avoid this hang forever on the connection to 3c  for any infrastructure or internet reason, i just add a timeout condition on request.
Testing and running uninterrupted for more then 24h.

**Comment by bogdanteodoru** [comment]
@cj4c0b1 I will merge as soon as you fix the conflicts. Thank you!
